version: "3.9"

services:
  web:
    build:
      context: "./app"
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 4000 --workers 4"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
        Databases:

  postgres:
    image: postgres:15-alpine
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
        Databases:
          aliases:
            - "postgres"
            


networks:
  Databases:

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: './volumes/pgdata'